# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Promptvm < Formula
  desc "The official CLI for the PromptVM platform"
  homepage "https://github.com/AIEngineering26/promptvm-cli"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.7.0/promptvm_0.7.0_darwin_amd64.tar.gz"
      sha256 "164f0dadb706d597e8e15e9dcc6a655286d841adce6ade584e994ec0d148a21c"

      define_method(:install) do
        bin.install "promptvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.7.0/promptvm_0.7.0_darwin_arm64.tar.gz"
      sha256 "c9fb7625e5b658cce07ad50ca7247e613f64665621ac4e27cd73cc5cfe8d9375"

      define_method(:install) do
        bin.install "promptvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.7.0/promptvm_0.7.0_linux_amd64.tar.gz"
      sha256 "ff361a73f6e8e98656e82262ac53a9765e3324ee5652082c61037e621340c807"
      define_method(:install) do
        bin.install "promptvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.7.0/promptvm_0.7.0_linux_arm64.tar.gz"
      sha256 "333652a4722ca4a51ca515fe0d859a444bd4177f92f3677fb76c8e9c10e2ad04"
      define_method(:install) do
        bin.install "promptvm"
      end
    end
  end

  def caveats
    <<~EOS
      On first run, promptvm installs a bundled "promptvm" agent skill into your
      Claude Code (~/.claude/skills) and Codex (~/.agents/skills) directories so
      agents already know how to use PromptVM. Manage it with `promptvm agent`
      (install / status / uninstall); disable auto-install with
      PROMPTVM_NO_AGENT_SKILL=1.
    EOS
  end

  test do
    system "#{bin}/promptvm", "version"
  end
end
