# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Promptvm < Formula
  desc "The official CLI for the PromptVM platform"
  homepage "https://github.com/AIEngineering26/promptvm-cli"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.11.1/promptvm_0.11.1_darwin_amd64.tar.gz"
      sha256 "54bd53813cabfca0b7fc17119826da3238c94c6739bd0c057141166843ea2061"

      define_method(:install) do
        bin.install "promptvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.11.1/promptvm_0.11.1_darwin_arm64.tar.gz"
      sha256 "9931612783aca81919fecd7263e7418c1cecaf09dff6246c41c85f113aa9dea7"

      define_method(:install) do
        bin.install "promptvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.11.1/promptvm_0.11.1_linux_amd64.tar.gz"
      sha256 "32410dce7d187cf3c5d9ef9e79f2fa29947317251daf8910f4e943503c289eab"
      define_method(:install) do
        bin.install "promptvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.11.1/promptvm_0.11.1_linux_arm64.tar.gz"
      sha256 "d84a289ff971ac749bd83de8666c2d765362e3e17f2feb71e745752029871174"
      define_method(:install) do
        bin.install "promptvm"
      end
    end
  end

  def caveats
    <<~EOS
      On first run, promptvm installs a bundled "promptvm" agent skill into your
      Claude Code (~/.claude/skills) and Codex (~/.agents/skills) directories so
      agents already know how to use PromptVM. Manage it with `promptvm agent`
      (install / status / uninstall); disable auto-install with
      PROMPTVM_NO_AGENT_SKILL=1.
    EOS
  end

  test do
    system "#{bin}/promptvm", "version"
  end
end
