# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Promptvm < Formula
  desc "The official CLI for the PromptVM platform"
  homepage "https://github.com/AIEngineering26/promptvm-cli"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.8.0/promptvm_0.8.0_darwin_amd64.tar.gz"
      sha256 "4cae4fe172a3ac7ae9bcfb0078b0fa2a3ef07a7de42efaa0d7af21a62f6e37c1"

      define_method(:install) do
        bin.install "promptvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.8.0/promptvm_0.8.0_darwin_arm64.tar.gz"
      sha256 "14738b9e4e20a094a823c8e6c792cde0d2ef19898b30eabf4c44dc24720d3db0"

      define_method(:install) do
        bin.install "promptvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.8.0/promptvm_0.8.0_linux_amd64.tar.gz"
      sha256 "0cc2aa74609fb0bfe7c63b9e593c1bab0b47ce0b736a95962f9e96074188e999"
      define_method(:install) do
        bin.install "promptvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AIEngineering26/promptvm-cli/releases/download/v0.8.0/promptvm_0.8.0_linux_arm64.tar.gz"
      sha256 "f5c40f8a0303e1f352f72b9fbd264bb237cf92128e9f2325d8a1046f57a31036"
      define_method(:install) do
        bin.install "promptvm"
      end
    end
  end

  def caveats
    <<~EOS
      On first run, promptvm installs a bundled "promptvm" agent skill into your
      Claude Code (~/.claude/skills) and Codex (~/.agents/skills) directories so
      agents already know how to use PromptVM. Manage it with `promptvm agent`
      (install / status / uninstall); disable auto-install with
      PROMPTVM_NO_AGENT_SKILL=1.
    EOS
  end

  test do
    system "#{bin}/promptvm", "version"
  end
end
